using System;
namespace xingwaWinFormUI.Win32.Com
{
	public enum DOCHOSTUIFLAG
	{
		DOCHOSTUIFLAG_DIALOG = 1,
		DOCHOSTUIFLAG_DISABLE_HELP_MENU,
		DOCHOSTUIFLAG_NO3DBORDER = 4,
		DOCHOSTUIFLAG_SCROLL_NO = 8,
		DOCHOSTUIFLAG_DISABLE_SCRIPT_INACTIVE = 16,
		DOCHOSTUIFLAG_OPENNEWWIN = 32,
		DOCHOSTUIFLAG_DISABLE_OFFSCREEN = 64,
		DOCHOSTUIFLAG_FLAT_SCROLLBAR = 128,
		DOCHOSTUIFLAG_DIV_BLOCKDEFAULT = 256,
		DOCHOSTUIFLAG_ACTIVATE_CLIENTHIT_ONLY = 512,
		DOCHOSTUIFLAG_OVERRIDEBEHAVIORFACTORY = 1024,
		DOCHOSTUIFLAG_CODEPAGELINKEDFONTS = 2048,
		DOCHOSTUIFLAG_URL_ENCODING_DISABLE_UTF8 = 4096,
		DOCHOSTUIFLAG_URL_ENCODING_ENABLE_UTF8 = 8192,
		DOCHOSTUIFLAG_ENABLE_FORMS_AUTOCOMPLETE = 16384,
		DOCHOSTUIFLAG_ENABLE_INPLACE_NAVIGATION = 65536,
		DOCHOSTUIFLAG_IME_ENABLE_RECONVERSION = 131072,
		DOCHOSTUIFLAG_THEME = 262144,
		DOCHOSTUIFLAG_NOTHEME = 524288,
		DOCHOSTUIFLAG_NOPICS = 1048576,
		DOCHOSTUIFLAG_NO3DOUTERBORDER = 2097152,
		DOCHOSTUIFLAG_DELEGATESIDOFDISPATCH = 4194304
	}
}
