using workfere.Properties;
using xingwaWinFormUI.SkinClass;
using xingwaWinFormUI.Win32;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
namespace xingwaWinFormUI.SkinControl
{
	public class PassKey : Form
	{
		private IContainer components;
		private SkinButtom btnDelet;
		private SkinButtom btnCapsLock;
		private SkinButtom btnClose;
		private SkinButtom btnShift;
		private SkinButtom btn7;
		private ToolTip toolShow;
		private SkinButtom btn8;
		private SkinButtom btn0;
		private SkinButtom btn9;
		private SkinButtom btn3;
		private SkinButtom btn2;
		private SkinButtom btn1;
		private SkinButtom btnd1;
		private SkinButtom btn6;
		private SkinButtom btn5;
		private SkinButtom btn4;
		private SkinButtom btnl;
		private SkinButtom btnk;
		private SkinButtom btnj;
		private SkinButtom btni;
		private SkinButtom btnh;
		private SkinButtom btng;
		private SkinButtom btnf;
		private SkinButtom btne;
		private SkinButtom btnd;
		private SkinButtom btnc;
		private SkinButtom btnb;
		private SkinButtom btna;
		private SkinButtom btnm;
		private SkinButtom btny;
		private SkinButtom btnx;
		private SkinButtom btnw;
		private SkinButtom btnv;
		private SkinButtom btnu;
		private SkinButtom btnt;
		private SkinButtom btns;
		private SkinButtom btnr;
		private SkinButtom btnq;
		private SkinButtom btnp;
		private SkinButtom btno;
		private SkinButtom btnn;
		private SkinButtom btnz;
		private SkinButtom btnhx2;
		private SkinButtom btndh;
		private SkinButtom btnjh;
		private SkinButtom btnhx;
		private SkinButtom btnd4;
		private SkinButtom btnd3;
		private SkinButtom btnd2;
		private SkinButtom btnMh;
		private SkinButtom btnKh2;
		private SkinButtom btnKh1;
		private SkinTextBox txt;
		private int X;
		private int Y;
		private Image Norml;
		private Image Mouse;
		private bool ToUpper;
		private bool flag;
		private Image Norml2;
		private Image Mouse2;
		private bool flag2;
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.components = new Container();
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(PassKey));
			this.toolShow = new ToolTip(this.components);
			this.btnClose = new SkinButtom();
			this.btnhx2 = new SkinButtom();
			this.btndh = new SkinButtom();
			this.btnjh = new SkinButtom();
			this.btnhx = new SkinButtom();
			this.btnd4 = new SkinButtom();
			this.btnd3 = new SkinButtom();
			this.btnd2 = new SkinButtom();
			this.btnMh = new SkinButtom();
			this.btnKh2 = new SkinButtom();
			this.btnKh1 = new SkinButtom();
			this.btny = new SkinButtom();
			this.btnx = new SkinButtom();
			this.btnw = new SkinButtom();
			this.btnv = new SkinButtom();
			this.btnu = new SkinButtom();
			this.btnt = new SkinButtom();
			this.btns = new SkinButtom();
			this.btnr = new SkinButtom();
			this.btnq = new SkinButtom();
			this.btnp = new SkinButtom();
			this.btno = new SkinButtom();
			this.btnn = new SkinButtom();
			this.btnz = new SkinButtom();
			this.btna = new SkinButtom();
			this.btnm = new SkinButtom();
			this.btnl = new SkinButtom();
			this.btnk = new SkinButtom();
			this.btnj = new SkinButtom();
			this.btni = new SkinButtom();
			this.btnh = new SkinButtom();
			this.btng = new SkinButtom();
			this.btnf = new SkinButtom();
			this.btne = new SkinButtom();
			this.btnd = new SkinButtom();
			this.btnc = new SkinButtom();
			this.btnb = new SkinButtom();
			this.btn6 = new SkinButtom();
			this.btn5 = new SkinButtom();
			this.btn4 = new SkinButtom();
			this.btn3 = new SkinButtom();
			this.btn2 = new SkinButtom();
			this.btn1 = new SkinButtom();
			this.btnd1 = new SkinButtom();
			this.btn0 = new SkinButtom();
			this.btn9 = new SkinButtom();
			this.btn8 = new SkinButtom();
			this.btn7 = new SkinButtom();
			this.btnShift = new SkinButtom();
			this.btnCapsLock = new SkinButtom();
			this.btnDelet = new SkinButtom();
			base.SuspendLayout();
			this.btnClose.BackColor = Color.Transparent;
			this.btnClose.BackgroundImage = Resources.Norml;
			this.btnClose.BackgroundImageLayout = ImageLayout.None;
			this.btnClose.ControlState = ControlState.Normal;
			this.btnClose.DownBack = Resources.BtnClose_hight;
			this.btnClose.DrawType = DrawStyle.Img;
			this.btnClose.Location = new Point(344, 5);
			this.btnClose.Margin = new Padding(0);
			this.btnClose.MouseBack = Resources.BtnClose_hight;
			this.btnClose.Name = "btnClose";
			this.btnClose.NormlBack = Resources.Norml;
			this.btnClose.Size = new Size(11, 11);
			this.btnClose.TabIndex = 2;
			this.btnClose.Tag = "3";
			this.toolShow.SetToolTip(this.btnClose, "关闭");
			this.btnClose.UseVisualStyleBackColor = false;
			this.btnClose.Click += new EventHandler(this.btnClose_Click);
			this.btnhx2.BackColor = Color.Transparent;
			this.btnhx2.BackgroundImage = Resources.Norml;
			this.btnhx2.BackgroundImageLayout = ImageLayout.None;
			this.btnhx2.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnhx2.ControlState = ControlState.Normal;
			this.btnhx2.DownBack = Resources.pushed;
			this.btnhx2.DrawType = DrawStyle.Img;
			this.btnhx2.Font = new Font("微软雅黑", 8.5f);
			this.btnhx2.Location = new Point(268, 30);
			this.btnhx2.Margin = new Padding(0);
			this.btnhx2.MouseBack = Resources.hight;
			this.btnhx2.Name = "btnhx2";
			this.btnhx2.NormlBack = Resources.Norml;
			this.btnhx2.Palace = true;
			this.btnhx2.Radius = 4;
			this.btnhx2.RoundStyle = RoundStyle.All;
			this.btnhx2.Size = new Size(24, 24);
			this.btnhx2.TabIndex = 50;
			this.btnhx2.Tag = "1|\\";
			this.btnhx2.Text = "\\";
			this.btnhx2.UseVisualStyleBackColor = false;
			this.btnhx2.Click += new EventHandler(this.btn_Click);
			this.btndh.BackColor = Color.Transparent;
			this.btndh.BackgroundImage = Resources.Norml;
			this.btndh.BackgroundImageLayout = ImageLayout.None;
			this.btndh.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btndh.ControlState = ControlState.Normal;
			this.btndh.DownBack = Resources.pushed;
			this.btndh.DrawType = DrawStyle.Img;
			this.btndh.Font = new Font("微软雅黑", 8.5f);
			this.btndh.Location = new Point(243, 30);
			this.btndh.Margin = new Padding(0);
			this.btndh.MouseBack = Resources.hight;
			this.btndh.Name = "btndh";
			this.btndh.NormlBack = Resources.Norml;
			this.btndh.Palace = true;
			this.btndh.Radius = 4;
			this.btndh.RoundStyle = RoundStyle.All;
			this.btndh.Size = new Size(24, 24);
			this.btndh.TabIndex = 49;
			this.btndh.Tag = "1+=";
			this.btndh.Text = "=";
			this.btndh.UseVisualStyleBackColor = false;
			this.btndh.Click += new EventHandler(this.btn_Click);
			this.btnjh.BackColor = Color.Transparent;
			this.btnjh.BackgroundImage = Resources.Norml;
			this.btnjh.BackgroundImageLayout = ImageLayout.None;
			this.btnjh.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnjh.ControlState = ControlState.Normal;
			this.btnjh.DownBack = Resources.pushed;
			this.btnjh.DrawType = DrawStyle.Img;
			this.btnjh.Font = new Font("微软雅黑", 8.5f);
			this.btnjh.Location = new Point(218, 30);
			this.btnjh.Margin = new Padding(0);
			this.btnjh.MouseBack = Resources.hight;
			this.btnjh.Name = "btnjh";
			this.btnjh.NormlBack = Resources.Norml;
			this.btnjh.Palace = true;
			this.btnjh.Radius = 4;
			this.btnjh.RoundStyle = RoundStyle.All;
			this.btnjh.Size = new Size(24, 24);
			this.btnjh.TabIndex = 48;
			this.btnjh.Tag = "1_-";
			this.btnjh.Text = "-";
			this.btnjh.UseVisualStyleBackColor = false;
			this.btnjh.Click += new EventHandler(this.btn_Click);
			this.btnhx.BackColor = Color.Transparent;
			this.btnhx.BackgroundImage = Resources.Norml;
			this.btnhx.BackgroundImageLayout = ImageLayout.None;
			this.btnhx.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnhx.ControlState = ControlState.Normal;
			this.btnhx.DownBack = Resources.pushed;
			this.btnhx.DrawType = DrawStyle.Img;
			this.btnhx.Font = new Font("微软雅黑", 8.5f);
			this.btnhx.Location = new Point(193, 30);
			this.btnhx.Margin = new Padding(0);
			this.btnhx.MouseBack = Resources.hight;
			this.btnhx.Name = "btnhx";
			this.btnhx.NormlBack = Resources.Norml;
			this.btnhx.Palace = true;
			this.btnhx.Radius = 4;
			this.btnhx.RoundStyle = RoundStyle.All;
			this.btnhx.Size = new Size(24, 24);
			this.btnhx.TabIndex = 47;
			this.btnhx.Tag = "1?/";
			this.btnhx.Text = "/";
			this.btnhx.UseVisualStyleBackColor = false;
			this.btnhx.Click += new EventHandler(this.btn_Click);
			this.btnd4.BackColor = Color.Transparent;
			this.btnd4.BackgroundImage = Resources.Norml;
			this.btnd4.BackgroundImageLayout = ImageLayout.None;
			this.btnd4.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnd4.ControlState = ControlState.Normal;
			this.btnd4.DownBack = Resources.pushed;
			this.btnd4.DrawType = DrawStyle.Img;
			this.btnd4.Font = new Font("微软雅黑", 8.5f);
			this.btnd4.Location = new Point(168, 30);
			this.btnd4.Margin = new Padding(0);
			this.btnd4.MouseBack = Resources.hight;
			this.btnd4.Name = "btnd4";
			this.btnd4.NormlBack = Resources.Norml;
			this.btnd4.Palace = true;
			this.btnd4.Radius = 4;
			this.btnd4.RoundStyle = RoundStyle.All;
			this.btnd4.Size = new Size(24, 24);
			this.btnd4.TabIndex = 46;
			this.btnd4.Tag = "1>.";
			this.btnd4.Text = ".";
			this.btnd4.UseVisualStyleBackColor = false;
			this.btnd4.Click += new EventHandler(this.btn_Click);
			this.btnd3.BackColor = Color.Transparent;
			this.btnd3.BackgroundImage = Resources.Norml;
			this.btnd3.BackgroundImageLayout = ImageLayout.None;
			this.btnd3.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnd3.ControlState = ControlState.Normal;
			this.btnd3.DownBack = Resources.pushed;
			this.btnd3.DrawType = DrawStyle.Img;
			this.btnd3.Font = new Font("微软雅黑", 8.5f);
			this.btnd3.Location = new Point(143, 30);
			this.btnd3.Margin = new Padding(0);
			this.btnd3.MouseBack = Resources.hight;
			this.btnd3.Name = "btnd3";
			this.btnd3.NormlBack = Resources.Norml;
			this.btnd3.Palace = true;
			this.btnd3.Radius = 4;
			this.btnd3.RoundStyle = RoundStyle.All;
			this.btnd3.Size = new Size(24, 24);
			this.btnd3.TabIndex = 45;
			this.btnd3.Tag = "1<,";
			this.btnd3.Text = ",";
			this.btnd3.UseVisualStyleBackColor = false;
			this.btnd3.Click += new EventHandler(this.btn_Click);
			this.btnd2.BackColor = Color.Transparent;
			this.btnd2.BackgroundImage = Resources.Norml;
			this.btnd2.BackgroundImageLayout = ImageLayout.None;
			this.btnd2.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnd2.ControlState = ControlState.Normal;
			this.btnd2.DownBack = Resources.pushed;
			this.btnd2.DrawType = DrawStyle.Img;
			this.btnd2.Font = new Font("微软雅黑", 8.5f);
			this.btnd2.Location = new Point(118, 30);
			this.btnd2.Margin = new Padding(0);
			this.btnd2.MouseBack = Resources.hight;
			this.btnd2.Name = "btnd2";
			this.btnd2.NormlBack = Resources.Norml;
			this.btnd2.Palace = true;
			this.btnd2.Radius = 4;
			this.btnd2.RoundStyle = RoundStyle.All;
			this.btnd2.Size = new Size(24, 24);
			this.btnd2.TabIndex = 44;
			this.btnd2.Tag = "1\"'";
			this.btnd2.Text = "'";
			this.btnd2.UseVisualStyleBackColor = false;
			this.btnd2.Click += new EventHandler(this.btn_Click);
			this.btnMh.BackColor = Color.Transparent;
			this.btnMh.BackgroundImage = Resources.Norml;
			this.btnMh.BackgroundImageLayout = ImageLayout.None;
			this.btnMh.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnMh.ControlState = ControlState.Normal;
			this.btnMh.DownBack = Resources.pushed;
			this.btnMh.DrawType = DrawStyle.Img;
			this.btnMh.Font = new Font("微软雅黑", 8.5f);
			this.btnMh.Location = new Point(93, 30);
			this.btnMh.Margin = new Padding(0);
			this.btnMh.MouseBack = Resources.hight;
			this.btnMh.Name = "btnMh";
			this.btnMh.NormlBack = Resources.Norml;
			this.btnMh.Palace = true;
			this.btnMh.Radius = 4;
			this.btnMh.RoundStyle = RoundStyle.All;
			this.btnMh.Size = new Size(24, 24);
			this.btnMh.TabIndex = 43;
			this.btnMh.Tag = "1:;";
			this.btnMh.Text = ";";
			this.btnMh.UseVisualStyleBackColor = false;
			this.btnMh.Click += new EventHandler(this.btn_Click);
			this.btnKh2.BackColor = Color.Transparent;
			this.btnKh2.BackgroundImage = Resources.Norml;
			this.btnKh2.BackgroundImageLayout = ImageLayout.None;
			this.btnKh2.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnKh2.ControlState = ControlState.Normal;
			this.btnKh2.DownBack = Resources.pushed;
			this.btnKh2.DrawType = DrawStyle.Img;
			this.btnKh2.Font = new Font("微软雅黑", 8.5f);
			this.btnKh2.Location = new Point(68, 30);
			this.btnKh2.Margin = new Padding(0);
			this.btnKh2.MouseBack = Resources.hight;
			this.btnKh2.Name = "btnKh2";
			this.btnKh2.NormlBack = Resources.Norml;
			this.btnKh2.Palace = true;
			this.btnKh2.Radius = 4;
			this.btnKh2.RoundStyle = RoundStyle.All;
			this.btnKh2.Size = new Size(24, 24);
			this.btnKh2.TabIndex = 42;
			this.btnKh2.Tag = "1}]";
			this.btnKh2.Text = "]";
			this.btnKh2.UseVisualStyleBackColor = false;
			this.btnKh2.Click += new EventHandler(this.btn_Click);
			this.btnKh1.BackColor = Color.Transparent;
			this.btnKh1.BackgroundImage = Resources.Norml;
			this.btnKh1.BackgroundImageLayout = ImageLayout.None;
			this.btnKh1.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnKh1.ControlState = ControlState.Normal;
			this.btnKh1.DownBack = Resources.pushed;
			this.btnKh1.DrawType = DrawStyle.Img;
			this.btnKh1.Font = new Font("微软雅黑", 8.5f);
			this.btnKh1.Location = new Point(43, 30);
			this.btnKh1.Margin = new Padding(0);
			this.btnKh1.MouseBack = Resources.hight;
			this.btnKh1.Name = "btnKh1";
			this.btnKh1.NormlBack = Resources.Norml;
			this.btnKh1.Palace = true;
			this.btnKh1.Radius = 4;
			this.btnKh1.RoundStyle = RoundStyle.All;
			this.btnKh1.Size = new Size(24, 24);
			this.btnKh1.TabIndex = 41;
			this.btnKh1.Tag = "1{[";
			this.btnKh1.Text = "[";
			this.btnKh1.UseVisualStyleBackColor = false;
			this.btnKh1.Click += new EventHandler(this.btn_Click);
			this.btny.BackColor = Color.Transparent;
			this.btny.BackgroundImage = Resources.Norml;
			this.btny.BackgroundImageLayout = ImageLayout.None;
			this.btny.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btny.ControlState = ControlState.Normal;
			this.btny.DownBack = Resources.pushed;
			this.btny.DrawType = DrawStyle.Img;
			this.btny.Font = new Font("微软雅黑", 8.5f);
			this.btny.Location = new Point(323, 82);
			this.btny.Margin = new Padding(0);
			this.btny.MouseBack = Resources.hight;
			this.btny.Name = "btny";
			this.btny.NormlBack = Resources.Norml;
			this.btny.Radius = 4;
			this.btny.RoundStyle = RoundStyle.All;
			this.btny.Size = new Size(25, 24);
			this.btny.TabIndex = 40;
			this.btny.Tag = "2";
			this.btny.Text = "y";
			this.btny.UseVisualStyleBackColor = false;
			this.btny.Click += new EventHandler(this.btn_Click);
			this.btnx.BackColor = Color.Transparent;
			this.btnx.BackgroundImage = Resources.Norml;
			this.btnx.BackgroundImageLayout = ImageLayout.None;
			this.btnx.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnx.ControlState = ControlState.Normal;
			this.btnx.DownBack = Resources.pushed;
			this.btnx.DrawType = DrawStyle.Img;
			this.btnx.Font = new Font("微软雅黑", 8.5f);
			this.btnx.Location = new Point(297, 82);
			this.btnx.Margin = new Padding(0);
			this.btnx.MouseBack = Resources.hight;
			this.btnx.Name = "btnx";
			this.btnx.NormlBack = Resources.Norml;
			this.btnx.Radius = 4;
			this.btnx.RoundStyle = RoundStyle.All;
			this.btnx.Size = new Size(25, 24);
			this.btnx.TabIndex = 39;
			this.btnx.Tag = "2";
			this.btnx.Text = "x";
			this.btnx.UseVisualStyleBackColor = false;
			this.btnx.Click += new EventHandler(this.btn_Click);
			this.btnw.BackColor = Color.Transparent;
			this.btnw.BackgroundImage = Resources.Norml;
			this.btnw.BackgroundImageLayout = ImageLayout.None;
			this.btnw.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnw.ControlState = ControlState.Normal;
			this.btnw.DownBack = Resources.pushed;
			this.btnw.DrawType = DrawStyle.Img;
			this.btnw.Font = new Font("微软雅黑", 8.5f);
			this.btnw.Location = new Point(271, 82);
			this.btnw.Margin = new Padding(0);
			this.btnw.MouseBack = Resources.hight;
			this.btnw.Name = "btnw";
			this.btnw.NormlBack = Resources.Norml;
			this.btnw.Radius = 4;
			this.btnw.RoundStyle = RoundStyle.All;
			this.btnw.Size = new Size(25, 24);
			this.btnw.TabIndex = 38;
			this.btnw.Tag = "2";
			this.btnw.Text = "w";
			this.btnw.UseVisualStyleBackColor = false;
			this.btnw.Click += new EventHandler(this.btn_Click);
			this.btnv.BackColor = Color.Transparent;
			this.btnv.BackgroundImage = Resources.Norml;
			this.btnv.BackgroundImageLayout = ImageLayout.None;
			this.btnv.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnv.ControlState = ControlState.Normal;
			this.btnv.DownBack = Resources.pushed;
			this.btnv.DrawType = DrawStyle.Img;
			this.btnv.Font = new Font("微软雅黑", 8.5f);
			this.btnv.Location = new Point(245, 82);
			this.btnv.Margin = new Padding(0);
			this.btnv.MouseBack = Resources.hight;
			this.btnv.Name = "btnv";
			this.btnv.NormlBack = Resources.Norml;
			this.btnv.Radius = 4;
			this.btnv.RoundStyle = RoundStyle.All;
			this.btnv.Size = new Size(25, 24);
			this.btnv.TabIndex = 37;
			this.btnv.Tag = "2";
			this.btnv.Text = "v";
			this.btnv.UseVisualStyleBackColor = false;
			this.btnv.Click += new EventHandler(this.btn_Click);
			this.btnu.BackColor = Color.Transparent;
			this.btnu.BackgroundImage = Resources.Norml;
			this.btnu.BackgroundImageLayout = ImageLayout.None;
			this.btnu.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnu.ControlState = ControlState.Normal;
			this.btnu.DownBack = Resources.pushed;
			this.btnu.DrawType = DrawStyle.Img;
			this.btnu.Font = new Font("微软雅黑", 8.5f);
			this.btnu.Location = new Point(219, 82);
			this.btnu.Margin = new Padding(0);
			this.btnu.MouseBack = Resources.hight;
			this.btnu.Name = "btnu";
			this.btnu.NormlBack = Resources.Norml;
			this.btnu.Radius = 4;
			this.btnu.RoundStyle = RoundStyle.All;
			this.btnu.Size = new Size(25, 24);
			this.btnu.TabIndex = 36;
			this.btnu.Tag = "2";
			this.btnu.Text = "u";
			this.btnu.UseVisualStyleBackColor = false;
			this.btnu.Click += new EventHandler(this.btn_Click);
			this.btnt.BackColor = Color.Transparent;
			this.btnt.BackgroundImage = Resources.Norml;
			this.btnt.BackgroundImageLayout = ImageLayout.None;
			this.btnt.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnt.ControlState = ControlState.Normal;
			this.btnt.DownBack = Resources.pushed;
			this.btnt.DrawType = DrawStyle.Img;
			this.btnt.Font = new Font("微软雅黑", 8.5f);
			this.btnt.Location = new Point(193, 82);
			this.btnt.Margin = new Padding(0);
			this.btnt.MouseBack = Resources.hight;
			this.btnt.Name = "btnt";
			this.btnt.NormlBack = Resources.Norml;
			this.btnt.Radius = 4;
			this.btnt.RoundStyle = RoundStyle.All;
			this.btnt.Size = new Size(25, 24);
			this.btnt.TabIndex = 35;
			this.btnt.Tag = "2";
			this.btnt.Text = "t";
			this.btnt.UseVisualStyleBackColor = false;
			this.btnt.Click += new EventHandler(this.btn_Click);
			this.btns.BackColor = Color.Transparent;
			this.btns.BackgroundImage = Resources.Norml;
			this.btns.BackgroundImageLayout = ImageLayout.None;
			this.btns.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btns.ControlState = ControlState.Normal;
			this.btns.DownBack = Resources.pushed;
			this.btns.DrawType = DrawStyle.Img;
			this.btns.Font = new Font("微软雅黑", 8.5f);
			this.btns.Location = new Point(167, 82);
			this.btns.Margin = new Padding(0);
			this.btns.MouseBack = Resources.hight;
			this.btns.Name = "btns";
			this.btns.NormlBack = Resources.Norml;
			this.btns.Radius = 4;
			this.btns.RoundStyle = RoundStyle.All;
			this.btns.Size = new Size(25, 24);
			this.btns.TabIndex = 34;
			this.btns.Tag = "2";
			this.btns.Text = "s";
			this.btns.UseVisualStyleBackColor = false;
			this.btns.Click += new EventHandler(this.btn_Click);
			this.btnr.BackColor = Color.Transparent;
			this.btnr.BackgroundImage = Resources.Norml;
			this.btnr.BackgroundImageLayout = ImageLayout.None;
			this.btnr.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnr.ControlState = ControlState.Normal;
			this.btnr.DownBack = Resources.pushed;
			this.btnr.DrawType = DrawStyle.Img;
			this.btnr.Font = new Font("微软雅黑", 8.5f);
			this.btnr.Location = new Point(141, 82);
			this.btnr.Margin = new Padding(0);
			this.btnr.MouseBack = Resources.hight;
			this.btnr.Name = "btnr";
			this.btnr.NormlBack = Resources.Norml;
			this.btnr.Radius = 4;
			this.btnr.RoundStyle = RoundStyle.All;
			this.btnr.Size = new Size(25, 24);
			this.btnr.TabIndex = 33;
			this.btnr.Tag = "2";
			this.btnr.Text = "r";
			this.btnr.UseVisualStyleBackColor = false;
			this.btnr.Click += new EventHandler(this.btn_Click);
			this.btnq.BackColor = Color.Transparent;
			this.btnq.BackgroundImage = Resources.Norml;
			this.btnq.BackgroundImageLayout = ImageLayout.None;
			this.btnq.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnq.ControlState = ControlState.Normal;
			this.btnq.DownBack = Resources.pushed;
			this.btnq.DrawType = DrawStyle.Img;
			this.btnq.Font = new Font("微软雅黑", 8.5f);
			this.btnq.Location = new Point(115, 82);
			this.btnq.Margin = new Padding(0);
			this.btnq.MouseBack = Resources.hight;
			this.btnq.Name = "btnq";
			this.btnq.NormlBack = Resources.Norml;
			this.btnq.Radius = 4;
			this.btnq.RoundStyle = RoundStyle.All;
			this.btnq.Size = new Size(25, 24);
			this.btnq.TabIndex = 32;
			this.btnq.Tag = "2";
			this.btnq.Text = "q";
			this.btnq.UseVisualStyleBackColor = false;
			this.btnq.Click += new EventHandler(this.btn_Click);
			this.btnp.BackColor = Color.Transparent;
			this.btnp.BackgroundImage = Resources.Norml;
			this.btnp.BackgroundImageLayout = ImageLayout.None;
			this.btnp.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnp.ControlState = ControlState.Normal;
			this.btnp.DownBack = Resources.pushed;
			this.btnp.DrawType = DrawStyle.Img;
			this.btnp.Font = new Font("微软雅黑", 8.5f);
			this.btnp.Location = new Point(89, 82);
			this.btnp.Margin = new Padding(0);
			this.btnp.MouseBack = Resources.hight;
			this.btnp.Name = "btnp";
			this.btnp.NormlBack = Resources.Norml;
			this.btnp.Radius = 4;
			this.btnp.RoundStyle = RoundStyle.All;
			this.btnp.Size = new Size(25, 24);
			this.btnp.TabIndex = 31;
			this.btnp.Tag = "2";
			this.btnp.Text = "p";
			this.btnp.UseVisualStyleBackColor = false;
			this.btnp.Click += new EventHandler(this.btn_Click);
			this.btno.BackColor = Color.Transparent;
			this.btno.BackgroundImage = Resources.Norml;
			this.btno.BackgroundImageLayout = ImageLayout.None;
			this.btno.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btno.ControlState = ControlState.Normal;
			this.btno.DownBack = Resources.pushed;
			this.btno.DrawType = DrawStyle.Img;
			this.btno.Font = new Font("微软雅黑", 8.5f);
			this.btno.Location = new Point(63, 82);
			this.btno.Margin = new Padding(0);
			this.btno.MouseBack = Resources.hight;
			this.btno.Name = "btno";
			this.btno.NormlBack = Resources.Norml;
			this.btno.Radius = 4;
			this.btno.RoundStyle = RoundStyle.All;
			this.btno.Size = new Size(25, 24);
			this.btno.TabIndex = 30;
			this.btno.Tag = "2";
			this.btno.Text = "o";
			this.btno.UseVisualStyleBackColor = false;
			this.btno.Click += new EventHandler(this.btn_Click);
			this.btnn.BackColor = Color.Transparent;
			this.btnn.BackgroundImage = Resources.Norml;
			this.btnn.BackgroundImageLayout = ImageLayout.None;
			this.btnn.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnn.ControlState = ControlState.Normal;
			this.btnn.DownBack = Resources.pushed;
			this.btnn.DrawType = DrawStyle.Img;
			this.btnn.Font = new Font("微软雅黑", 8.5f);
			this.btnn.Location = new Point(37, 82);
			this.btnn.Margin = new Padding(0);
			this.btnn.MouseBack = Resources.hight;
			this.btnn.Name = "btnn";
			this.btnn.NormlBack = Resources.Norml;
			this.btnn.Radius = 4;
			this.btnn.RoundStyle = RoundStyle.All;
			this.btnn.Size = new Size(25, 24);
			this.btnn.TabIndex = 29;
			this.btnn.Tag = "2";
			this.btnn.Text = "n";
			this.btnn.UseVisualStyleBackColor = false;
			this.btnn.Click += new EventHandler(this.btn_Click);
			this.btnz.BackColor = Color.Transparent;
			this.btnz.BackgroundImage = Resources.Norml;
			this.btnz.BackgroundImageLayout = ImageLayout.None;
			this.btnz.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnz.ControlState = ControlState.Normal;
			this.btnz.DownBack = Resources.pushed;
			this.btnz.DrawType = DrawStyle.Img;
			this.btnz.Font = new Font("微软雅黑", 8.5f);
			this.btnz.Location = new Point(11, 82);
			this.btnz.Margin = new Padding(0);
			this.btnz.MouseBack = Resources.hight;
			this.btnz.Name = "btnz";
			this.btnz.NormlBack = Resources.Norml;
			this.btnz.Radius = 4;
			this.btnz.RoundStyle = RoundStyle.All;
			this.btnz.Size = new Size(25, 24);
			this.btnz.TabIndex = 28;
			this.btnz.Tag = "2";
			this.btnz.Text = "z";
			this.btnz.UseVisualStyleBackColor = false;
			this.btnz.Click += new EventHandler(this.btn_Click);
			this.btna.BackColor = Color.Transparent;
			this.btna.BackgroundImage = Resources.Norml;
			this.btna.BackgroundImageLayout = ImageLayout.None;
			this.btna.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btna.ControlState = ControlState.Normal;
			this.btna.DownBack = Resources.pushed;
			this.btna.DrawType = DrawStyle.Img;
			this.btna.Font = new Font("微软雅黑", 8.5f);
			this.btna.Location = new Point(323, 56);
			this.btna.Margin = new Padding(0);
			this.btna.MouseBack = Resources.hight;
			this.btna.Name = "btna";
			this.btna.NormlBack = Resources.Norml;
			this.btna.Radius = 4;
			this.btna.RoundStyle = RoundStyle.All;
			this.btna.Size = new Size(25, 24);
			this.btna.TabIndex = 27;
			this.btna.Tag = "2";
			this.btna.Text = "a";
			this.btna.UseVisualStyleBackColor = false;
			this.btna.Click += new EventHandler(this.btn_Click);
			this.btnm.BackColor = Color.Transparent;
			this.btnm.BackgroundImage = Resources.Norml;
			this.btnm.BackgroundImageLayout = ImageLayout.None;
			this.btnm.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnm.ControlState = ControlState.Normal;
			this.btnm.DownBack = Resources.pushed;
			this.btnm.DrawType = DrawStyle.Img;
			this.btnm.Font = new Font("微软雅黑", 8.5f);
			this.btnm.Location = new Point(297, 56);
			this.btnm.Margin = new Padding(0);
			this.btnm.MouseBack = Resources.hight;
			this.btnm.Name = "btnm";
			this.btnm.NormlBack = Resources.Norml;
			this.btnm.Radius = 4;
			this.btnm.RoundStyle = RoundStyle.All;
			this.btnm.Size = new Size(25, 24);
			this.btnm.TabIndex = 26;
			this.btnm.Tag = "2";
			this.btnm.Text = "m";
			this.btnm.UseVisualStyleBackColor = false;
			this.btnm.Click += new EventHandler(this.btn_Click);
			this.btnl.BackColor = Color.Transparent;
			this.btnl.BackgroundImage = Resources.Norml;
			this.btnl.BackgroundImageLayout = ImageLayout.None;
			this.btnl.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnl.ControlState = ControlState.Normal;
			this.btnl.DownBack = Resources.pushed;
			this.btnl.DrawType = DrawStyle.Img;
			this.btnl.Font = new Font("微软雅黑", 8.5f);
			this.btnl.Location = new Point(271, 56);
			this.btnl.Margin = new Padding(0);
			this.btnl.MouseBack = Resources.hight;
			this.btnl.Name = "btnl";
			this.btnl.NormlBack = Resources.Norml;
			this.btnl.Radius = 4;
			this.btnl.RoundStyle = RoundStyle.All;
			this.btnl.Size = new Size(25, 24);
			this.btnl.TabIndex = 25;
			this.btnl.Tag = "2";
			this.btnl.Text = "l";
			this.btnl.UseVisualStyleBackColor = false;
			this.btnl.Click += new EventHandler(this.btn_Click);
			this.btnk.BackColor = Color.Transparent;
			this.btnk.BackgroundImage = Resources.Norml;
			this.btnk.BackgroundImageLayout = ImageLayout.None;
			this.btnk.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnk.ControlState = ControlState.Normal;
			this.btnk.DownBack = Resources.pushed;
			this.btnk.DrawType = DrawStyle.Img;
			this.btnk.Font = new Font("微软雅黑", 8.5f);
			this.btnk.Location = new Point(245, 56);
			this.btnk.Margin = new Padding(0);
			this.btnk.MouseBack = Resources.hight;
			this.btnk.Name = "btnk";
			this.btnk.NormlBack = Resources.Norml;
			this.btnk.Radius = 4;
			this.btnk.RoundStyle = RoundStyle.All;
			this.btnk.Size = new Size(25, 24);
			this.btnk.TabIndex = 24;
			this.btnk.Tag = "2";
			this.btnk.Text = "k";
			this.btnk.UseVisualStyleBackColor = false;
			this.btnk.Click += new EventHandler(this.btn_Click);
			this.btnj.BackColor = Color.Transparent;
			this.btnj.BackgroundImage = Resources.Norml;
			this.btnj.BackgroundImageLayout = ImageLayout.None;
			this.btnj.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnj.ControlState = ControlState.Normal;
			this.btnj.DownBack = Resources.pushed;
			this.btnj.DrawType = DrawStyle.Img;
			this.btnj.Font = new Font("微软雅黑", 8.5f);
			this.btnj.Location = new Point(219, 56);
			this.btnj.Margin = new Padding(0);
			this.btnj.MouseBack = Resources.hight;
			this.btnj.Name = "btnj";
			this.btnj.NormlBack = Resources.Norml;
			this.btnj.Radius = 4;
			this.btnj.RoundStyle = RoundStyle.All;
			this.btnj.Size = new Size(25, 24);
			this.btnj.TabIndex = 23;
			this.btnj.Tag = "2";
			this.btnj.Text = "j";
			this.btnj.UseVisualStyleBackColor = false;
			this.btnj.Click += new EventHandler(this.btn_Click);
			this.btni.BackColor = Color.Transparent;
			this.btni.BackgroundImage = Resources.Norml;
			this.btni.BackgroundImageLayout = ImageLayout.None;
			this.btni.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btni.ControlState = ControlState.Normal;
			this.btni.DownBack = Resources.pushed;
			this.btni.DrawType = DrawStyle.Img;
			this.btni.Font = new Font("微软雅黑", 8.5f);
			this.btni.Location = new Point(193, 56);
			this.btni.Margin = new Padding(0);
			this.btni.MouseBack = Resources.hight;
			this.btni.Name = "btni";
			this.btni.NormlBack = Resources.Norml;
			this.btni.Radius = 4;
			this.btni.RoundStyle = RoundStyle.All;
			this.btni.Size = new Size(25, 24);
			this.btni.TabIndex = 22;
			this.btni.Tag = "2";
			this.btni.Text = "i";
			this.btni.UseVisualStyleBackColor = false;
			this.btni.Click += new EventHandler(this.btn_Click);
			this.btnh.BackColor = Color.Transparent;
			this.btnh.BackgroundImage = Resources.Norml;
			this.btnh.BackgroundImageLayout = ImageLayout.None;
			this.btnh.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnh.ControlState = ControlState.Normal;
			this.btnh.DownBack = Resources.pushed;
			this.btnh.DrawType = DrawStyle.Img;
			this.btnh.Font = new Font("微软雅黑", 8.5f);
			this.btnh.Location = new Point(167, 56);
			this.btnh.Margin = new Padding(0);
			this.btnh.MouseBack = Resources.hight;
			this.btnh.Name = "btnh";
			this.btnh.NormlBack = Resources.Norml;
			this.btnh.Radius = 4;
			this.btnh.RoundStyle = RoundStyle.All;
			this.btnh.Size = new Size(25, 24);
			this.btnh.TabIndex = 21;
			this.btnh.Tag = "2";
			this.btnh.Text = "h";
			this.btnh.UseVisualStyleBackColor = false;
			this.btnh.Click += new EventHandler(this.btn_Click);
			this.btng.BackColor = Color.Transparent;
			this.btng.BackgroundImage = Resources.Norml;
			this.btng.BackgroundImageLayout = ImageLayout.None;
			this.btng.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btng.ControlState = ControlState.Normal;
			this.btng.DownBack = Resources.pushed;
			this.btng.DrawType = DrawStyle.Img;
			this.btng.Font = new Font("微软雅黑", 8.5f);
			this.btng.Location = new Point(141, 56);
			this.btng.Margin = new Padding(0);
			this.btng.MouseBack = Resources.hight;
			this.btng.Name = "btng";
			this.btng.NormlBack = Resources.Norml;
			this.btng.Radius = 4;
			this.btng.RoundStyle = RoundStyle.All;
			this.btng.Size = new Size(25, 24);
			this.btng.TabIndex = 20;
			this.btng.Tag = "2";
			this.btng.Text = "g";
			this.btng.UseVisualStyleBackColor = false;
			this.btng.Click += new EventHandler(this.btn_Click);
			this.btnf.BackColor = Color.Transparent;
			this.btnf.BackgroundImage = Resources.Norml;
			this.btnf.BackgroundImageLayout = ImageLayout.None;
			this.btnf.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnf.ControlState = ControlState.Normal;
			this.btnf.DownBack = Resources.pushed;
			this.btnf.DrawType = DrawStyle.Img;
			this.btnf.Font = new Font("微软雅黑", 8.5f);
			this.btnf.Location = new Point(115, 56);
			this.btnf.Margin = new Padding(0);
			this.btnf.MouseBack = Resources.hight;
			this.btnf.Name = "btnf";
			this.btnf.NormlBack = Resources.Norml;
			this.btnf.Radius = 4;
			this.btnf.RoundStyle = RoundStyle.All;
			this.btnf.Size = new Size(25, 24);
			this.btnf.TabIndex = 19;
			this.btnf.Tag = "2";
			this.btnf.Text = "f";
			this.btnf.UseVisualStyleBackColor = false;
			this.btnf.Click += new EventHandler(this.btn_Click);
			this.btne.BackColor = Color.Transparent;
			this.btne.BackgroundImage = Resources.Norml;
			this.btne.BackgroundImageLayout = ImageLayout.None;
			this.btne.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btne.ControlState = ControlState.Normal;
			this.btne.DownBack = Resources.pushed;
			this.btne.DrawType = DrawStyle.Img;
			this.btne.Font = new Font("微软雅黑", 8.5f);
			this.btne.Location = new Point(89, 56);
			this.btne.Margin = new Padding(0);
			this.btne.MouseBack = Resources.hight;
			this.btne.Name = "btne";
			this.btne.NormlBack = Resources.Norml;
			this.btne.Radius = 4;
			this.btne.RoundStyle = RoundStyle.All;
			this.btne.Size = new Size(25, 24);
			this.btne.TabIndex = 18;
			this.btne.Tag = "2";
			this.btne.Text = "e";
			this.btne.UseVisualStyleBackColor = false;
			this.btne.Click += new EventHandler(this.btn_Click);
			this.btnd.BackColor = Color.Transparent;
			this.btnd.BackgroundImage = Resources.Norml;
			this.btnd.BackgroundImageLayout = ImageLayout.None;
			this.btnd.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnd.ControlState = ControlState.Normal;
			this.btnd.DownBack = Resources.pushed;
			this.btnd.DrawType = DrawStyle.Img;
			this.btnd.Font = new Font("微软雅黑", 8.5f);
			this.btnd.Location = new Point(63, 56);
			this.btnd.Margin = new Padding(0);
			this.btnd.MouseBack = Resources.hight;
			this.btnd.Name = "btnd";
			this.btnd.NormlBack = Resources.Norml;
			this.btnd.Radius = 4;
			this.btnd.RoundStyle = RoundStyle.All;
			this.btnd.Size = new Size(25, 24);
			this.btnd.TabIndex = 17;
			this.btnd.Tag = "2";
			this.btnd.Text = "d";
			this.btnd.UseVisualStyleBackColor = false;
			this.btnd.Click += new EventHandler(this.btn_Click);
			this.btnc.BackColor = Color.Transparent;
			this.btnc.BackgroundImage = Resources.Norml;
			this.btnc.BackgroundImageLayout = ImageLayout.None;
			this.btnc.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnc.ControlState = ControlState.Normal;
			this.btnc.DownBack = Resources.pushed;
			this.btnc.DrawType = DrawStyle.Img;
			this.btnc.Font = new Font("微软雅黑", 8.5f);
			this.btnc.Location = new Point(37, 56);
			this.btnc.Margin = new Padding(0);
			this.btnc.MouseBack = Resources.hight;
			this.btnc.Name = "btnc";
			this.btnc.NormlBack = Resources.Norml;
			this.btnc.Radius = 4;
			this.btnc.RoundStyle = RoundStyle.All;
			this.btnc.Size = new Size(25, 24);
			this.btnc.TabIndex = 16;
			this.btnc.Tag = "2";
			this.btnc.Text = "c";
			this.btnc.UseVisualStyleBackColor = false;
			this.btnc.Click += new EventHandler(this.btn_Click);
			this.btnb.BackColor = Color.Transparent;
			this.btnb.BackgroundImage = Resources.Norml;
			this.btnb.BackgroundImageLayout = ImageLayout.None;
			this.btnb.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnb.ControlState = ControlState.Normal;
			this.btnb.DownBack = Resources.pushed;
			this.btnb.DrawType = DrawStyle.Img;
			this.btnb.Font = new Font("微软雅黑", 8.5f);
			this.btnb.Location = new Point(11, 56);
			this.btnb.Margin = new Padding(0);
			this.btnb.MouseBack = Resources.hight;
			this.btnb.Name = "btnb";
			this.btnb.NormlBack = Resources.Norml;
			this.btnb.Radius = 4;
			this.btnb.RoundStyle = RoundStyle.All;
			this.btnb.Size = new Size(25, 24);
			this.btnb.TabIndex = 15;
			this.btnb.Tag = "2";
			this.btnb.Text = "b";
			this.btnb.UseVisualStyleBackColor = false;
			this.btnb.Click += new EventHandler(this.btn_Click);
			this.btn6.BackColor = Color.Transparent;
			this.btn6.BackgroundImage = Resources.Norml;
			this.btn6.BackgroundImageLayout = ImageLayout.None;
			this.btn6.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn6.ControlState = ControlState.Normal;
			this.btn6.DownBack = Resources.pushed;
			this.btn6.DrawType = DrawStyle.Img;
			this.btn6.Font = new Font("微软雅黑", 8.5f);
			this.btn6.Location = new Point(271, 4);
			this.btn6.Margin = new Padding(0);
			this.btn6.MouseBack = Resources.hight;
			this.btn6.Name = "btn6";
			this.btn6.NormlBack = Resources.Norml;
			this.btn6.Radius = 4;
			this.btn6.RoundStyle = RoundStyle.All;
			this.btn6.Size = new Size(25, 24);
			this.btn6.TabIndex = 14;
			this.btn6.Tag = "1^6";
			this.btn6.Text = "6";
			this.btn6.UseVisualStyleBackColor = false;
			this.btn6.Click += new EventHandler(this.btn_Click);
			this.btn5.BackColor = Color.Transparent;
			this.btn5.BackgroundImage = Resources.Norml;
			this.btn5.BackgroundImageLayout = ImageLayout.None;
			this.btn5.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn5.ControlState = ControlState.Normal;
			this.btn5.DownBack = Resources.pushed;
			this.btn5.DrawType = DrawStyle.Img;
			this.btn5.Font = new Font("微软雅黑", 8.5f);
			this.btn5.Location = new Point(245, 4);
			this.btn5.Margin = new Padding(0);
			this.btn5.MouseBack = Resources.hight;
			this.btn5.Name = "btn5";
			this.btn5.NormlBack = Resources.Norml;
			this.btn5.Radius = 4;
			this.btn5.RoundStyle = RoundStyle.All;
			this.btn5.Size = new Size(25, 24);
			this.btn5.TabIndex = 13;
			this.btn5.Tag = "1%5";
			this.btn5.Text = "5";
			this.btn5.UseVisualStyleBackColor = false;
			this.btn5.Click += new EventHandler(this.btn_Click);
			this.btn4.BackColor = Color.Transparent;
			this.btn4.BackgroundImage = Resources.Norml;
			this.btn4.BackgroundImageLayout = ImageLayout.None;
			this.btn4.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn4.ControlState = ControlState.Normal;
			this.btn4.DownBack = Resources.pushed;
			this.btn4.DrawType = DrawStyle.Img;
			this.btn4.Font = new Font("微软雅黑", 8.5f);
			this.btn4.Location = new Point(219, 4);
			this.btn4.Margin = new Padding(0);
			this.btn4.MouseBack = Resources.hight;
			this.btn4.Name = "btn4";
			this.btn4.NormlBack = Resources.Norml;
			this.btn4.Radius = 4;
			this.btn4.RoundStyle = RoundStyle.All;
			this.btn4.Size = new Size(25, 24);
			this.btn4.TabIndex = 12;
			this.btn4.Tag = "1$4";
			this.btn4.Text = "4";
			this.btn4.UseVisualStyleBackColor = false;
			this.btn4.Click += new EventHandler(this.btn_Click);
			this.btn3.BackColor = Color.Transparent;
			this.btn3.BackgroundImage = Resources.Norml;
			this.btn3.BackgroundImageLayout = ImageLayout.None;
			this.btn3.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn3.ControlState = ControlState.Normal;
			this.btn3.DownBack = Resources.pushed;
			this.btn3.DrawType = DrawStyle.Img;
			this.btn3.Font = new Font("微软雅黑", 8.5f);
			this.btn3.Location = new Point(193, 4);
			this.btn3.Margin = new Padding(0);
			this.btn3.MouseBack = Resources.hight;
			this.btn3.Name = "btn3";
			this.btn3.NormlBack = Resources.Norml;
			this.btn3.Radius = 4;
			this.btn3.RoundStyle = RoundStyle.All;
			this.btn3.Size = new Size(25, 24);
			this.btn3.TabIndex = 11;
			this.btn3.Tag = "1#3";
			this.btn3.Text = "3";
			this.btn3.UseVisualStyleBackColor = false;
			this.btn3.Click += new EventHandler(this.btn_Click);
			this.btn2.BackColor = Color.Transparent;
			this.btn2.BackgroundImage = Resources.Norml;
			this.btn2.BackgroundImageLayout = ImageLayout.None;
			this.btn2.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn2.ControlState = ControlState.Normal;
			this.btn2.DownBack = Resources.pushed;
			this.btn2.DrawType = DrawStyle.Img;
			this.btn2.Font = new Font("微软雅黑", 8.5f);
			this.btn2.Location = new Point(167, 4);
			this.btn2.Margin = new Padding(0);
			this.btn2.MouseBack = Resources.hight;
			this.btn2.Name = "btn2";
			this.btn2.NormlBack = Resources.Norml;
			this.btn2.Radius = 4;
			this.btn2.RoundStyle = RoundStyle.All;
			this.btn2.Size = new Size(25, 24);
			this.btn2.TabIndex = 10;
			this.btn2.Tag = "1@2";
			this.btn2.Text = "2";
			this.btn2.UseVisualStyleBackColor = false;
			this.btn2.Click += new EventHandler(this.btn_Click);
			this.btn1.BackColor = Color.Transparent;
			this.btn1.BackgroundImage = Resources.Norml;
			this.btn1.BackgroundImageLayout = ImageLayout.None;
			this.btn1.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn1.ControlState = ControlState.Normal;
			this.btn1.DownBack = Resources.pushed;
			this.btn1.DrawType = DrawStyle.Img;
			this.btn1.Font = new Font("微软雅黑", 8.5f);
			this.btn1.Location = new Point(141, 4);
			this.btn1.Margin = new Padding(0);
			this.btn1.MouseBack = Resources.hight;
			this.btn1.Name = "btn1";
			this.btn1.NormlBack = Resources.Norml;
			this.btn1.Radius = 4;
			this.btn1.RoundStyle = RoundStyle.All;
			this.btn1.Size = new Size(25, 24);
			this.btn1.TabIndex = 9;
			this.btn1.Tag = "1!1";
			this.btn1.Text = "1";
			this.btn1.UseVisualStyleBackColor = false;
			this.btn1.Click += new EventHandler(this.btn_Click);
			this.btnd1.BackColor = Color.Transparent;
			this.btnd1.BackgroundImage = Resources.Norml;
			this.btnd1.BackgroundImageLayout = ImageLayout.None;
			this.btnd1.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnd1.ControlState = ControlState.Normal;
			this.btnd1.DownBack = Resources.pushed;
			this.btnd1.DrawType = DrawStyle.Img;
			this.btnd1.Font = new Font("微软雅黑", 8.5f);
			this.btnd1.Location = new Point(115, 4);
			this.btnd1.Margin = new Padding(0);
			this.btnd1.MouseBack = Resources.hight;
			this.btnd1.Name = "btnd1";
			this.btnd1.NormlBack = Resources.Norml;
			this.btnd1.Radius = 4;
			this.btnd1.RoundStyle = RoundStyle.All;
			this.btnd1.Size = new Size(25, 24);
			this.btnd1.TabIndex = 8;
			this.btnd1.Tag = "1~`";
			this.btnd1.Text = "`";
			this.btnd1.UseVisualStyleBackColor = false;
			this.btnd1.Click += new EventHandler(this.btn_Click);
			this.btn0.BackColor = Color.Transparent;
			this.btn0.BackgroundImage = Resources.Norml;
			this.btn0.BackgroundImageLayout = ImageLayout.None;
			this.btn0.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn0.ControlState = ControlState.Normal;
			this.btn0.DownBack = Resources.pushed;
			this.btn0.DrawType = DrawStyle.Img;
			this.btn0.Font = new Font("微软雅黑", 8.5f);
			this.btn0.Location = new Point(89, 4);
			this.btn0.Margin = new Padding(0);
			this.btn0.MouseBack = Resources.hight;
			this.btn0.Name = "btn0";
			this.btn0.NormlBack = Resources.Norml;
			this.btn0.Radius = 4;
			this.btn0.RoundStyle = RoundStyle.All;
			this.btn0.Size = new Size(25, 24);
			this.btn0.TabIndex = 7;
			this.btn0.Tag = "1)0";
			this.btn0.Text = "0";
			this.btn0.UseVisualStyleBackColor = false;
			this.btn0.Click += new EventHandler(this.btn_Click);
			this.btn9.BackColor = Color.Transparent;
			this.btn9.BackgroundImage = Resources.Norml;
			this.btn9.BackgroundImageLayout = ImageLayout.None;
			this.btn9.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn9.ControlState = ControlState.Normal;
			this.btn9.DownBack = Resources.pushed;
			this.btn9.DrawType = DrawStyle.Img;
			this.btn9.Font = new Font("微软雅黑", 8.5f);
			this.btn9.Location = new Point(63, 4);
			this.btn9.Margin = new Padding(0);
			this.btn9.MouseBack = Resources.hight;
			this.btn9.Name = "btn9";
			this.btn9.NormlBack = Resources.Norml;
			this.btn9.Radius = 4;
			this.btn9.RoundStyle = RoundStyle.All;
			this.btn9.Size = new Size(25, 24);
			this.btn9.TabIndex = 6;
			this.btn9.Tag = "1(9";
			this.btn9.Text = "9";
			this.btn9.UseVisualStyleBackColor = false;
			this.btn9.Click += new EventHandler(this.btn_Click);
			this.btn8.BackColor = Color.Transparent;
			this.btn8.BackgroundImage = Resources.Norml;
			this.btn8.BackgroundImageLayout = ImageLayout.None;
			this.btn8.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn8.ControlState = ControlState.Normal;
			this.btn8.DownBack = Resources.pushed;
			this.btn8.DrawType = DrawStyle.Img;
			this.btn8.Font = new Font("微软雅黑", 8.5f);
			this.btn8.Location = new Point(37, 4);
			this.btn8.Margin = new Padding(0);
			this.btn8.MouseBack = Resources.hight;
			this.btn8.Name = "btn8";
			this.btn8.NormlBack = Resources.Norml;
			this.btn8.Radius = 4;
			this.btn8.RoundStyle = RoundStyle.All;
			this.btn8.Size = new Size(25, 24);
			this.btn8.TabIndex = 5;
			this.btn8.Tag = "1*8";
			this.btn8.Text = "8";
			this.btn8.UseVisualStyleBackColor = false;
			this.btn8.Click += new EventHandler(this.btn_Click);
			this.btn7.BackColor = Color.Transparent;
			this.btn7.BackgroundImage = Resources.Norml;
			this.btn7.BackgroundImageLayout = ImageLayout.None;
			this.btn7.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btn7.ControlState = ControlState.Normal;
			this.btn7.DownBack = Resources.pushed;
			this.btn7.DrawType = DrawStyle.Img;
			this.btn7.Font = new Font("微软雅黑", 8.5f);
			this.btn7.Location = new Point(11, 4);
			this.btn7.Margin = new Padding(0);
			this.btn7.MouseBack = Resources.hight;
			this.btn7.Name = "btn7";
			this.btn7.NormlBack = Resources.Norml;
			this.btn7.Radius = 4;
			this.btn7.RoundStyle = RoundStyle.All;
			this.btn7.Size = new Size(25, 24);
			this.btn7.TabIndex = 4;
			this.btn7.Tag = "1&7";
			this.btn7.Text = "7";
			this.btn7.UseVisualStyleBackColor = false;
			this.btn7.Click += new EventHandler(this.btn_Click);
			this.btnShift.BackColor = Color.Transparent;
			this.btnShift.BackgroundImage = Resources.Norml;
			this.btnShift.BackgroundImageLayout = ImageLayout.None;
			this.btnShift.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnShift.ControlState = ControlState.Normal;
			this.btnShift.DownBack = Resources.pushed;
			this.btnShift.DrawType = DrawStyle.Img;
			this.btnShift.Font = new Font("微软雅黑", 8.5f);
			this.btnShift.Location = new Point(3, 30);
			this.btnShift.Margin = new Padding(0);
			this.btnShift.MouseBack = Resources.hight;
			this.btnShift.Name = "btnShift";
			this.btnShift.NormlBack = Resources.Norml;
			this.btnShift.Palace = true;
			this.btnShift.Radius = 4;
			this.btnShift.RoundStyle = RoundStyle.All;
			this.btnShift.Size = new Size(40, 24);
			this.btnShift.TabIndex = 3;
			this.btnShift.Tag = "3";
			this.btnShift.Text = "Shift";
			this.btnShift.UseVisualStyleBackColor = false;
			this.btnShift.Click += new EventHandler(this.btnShift_Click);
			this.btnCapsLock.BackColor = Color.Transparent;
			this.btnCapsLock.BackgroundImage = Resources.Norml;
			this.btnCapsLock.BackgroundImageLayout = ImageLayout.None;
			this.btnCapsLock.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnCapsLock.ControlState = ControlState.Normal;
			this.btnCapsLock.DownBack = Resources.pushed;
			this.btnCapsLock.DrawType = DrawStyle.Img;
			this.btnCapsLock.Font = new Font("微软雅黑", 8.5f);
			this.btnCapsLock.Location = new Point(293, 30);
			this.btnCapsLock.Margin = new Padding(0);
			this.btnCapsLock.MouseBack = Resources.hight;
			this.btnCapsLock.Name = "btnCapsLock";
			this.btnCapsLock.NormlBack = Resources.Norml;
			this.btnCapsLock.Palace = true;
			this.btnCapsLock.Radius = 4;
			this.btnCapsLock.RoundStyle = RoundStyle.All;
			this.btnCapsLock.Size = new Size(64, 24);
			this.btnCapsLock.TabIndex = 1;
			this.btnCapsLock.Tag = "3";
			this.btnCapsLock.Text = "Caps Lock";
			this.btnCapsLock.UseVisualStyleBackColor = false;
			this.btnCapsLock.Click += new EventHandler(this.btnCapsLock_Click);
			this.btnDelet.BackColor = Color.Transparent;
			this.btnDelet.BackgroundImage = Resources.Norml;
			this.btnDelet.BackgroundImageLayout = ImageLayout.None;
			this.btnDelet.BackRectangle = new Rectangle(4, 4, 4, 4);
			this.btnDelet.ControlState = ControlState.Normal;
			this.btnDelet.DownBack = Resources.pushed;
			this.btnDelet.DrawType = DrawStyle.Img;
			this.btnDelet.Font = new Font("微软雅黑", 8.5f);
			this.btnDelet.Location = new Point(297, 4);
			this.btnDelet.Margin = new Padding(0);
			this.btnDelet.MouseBack = Resources.hight;
			this.btnDelet.Name = "btnDelet";
			this.btnDelet.NormlBack = Resources.Norml;
			this.btnDelet.Palace = true;
			this.btnDelet.Radius = 4;
			this.btnDelet.RoundStyle = RoundStyle.All;
			this.btnDelet.Size = new Size(45, 24);
			this.btnDelet.TabIndex = 0;
			this.btnDelet.Tag = "3";
			this.btnDelet.Text = "←";
			this.btnDelet.UseVisualStyleBackColor = false;
			this.btnDelet.Click += new EventHandler(this.btnDelet_Click);
			base.AutoScaleMode = AutoScaleMode.None;
			this.BackColor = Color.White;
			this.BackgroundImage = (Image)componentResourceManager.GetObject("$this.BackgroundImage");
			this.BackgroundImageLayout = ImageLayout.None;
			base.ClientSize = new Size(360, 110);
			base.ControlBox = false;
			base.Controls.Add(this.btnhx2);
			base.Controls.Add(this.btndh);
			base.Controls.Add(this.btnjh);
			base.Controls.Add(this.btnhx);
			base.Controls.Add(this.btnd4);
			base.Controls.Add(this.btnd3);
			base.Controls.Add(this.btnd2);
			base.Controls.Add(this.btnMh);
			base.Controls.Add(this.btnKh2);
			base.Controls.Add(this.btnKh1);
			base.Controls.Add(this.btny);
			base.Controls.Add(this.btnx);
			base.Controls.Add(this.btnw);
			base.Controls.Add(this.btnv);
			base.Controls.Add(this.btnu);
			base.Controls.Add(this.btnt);
			base.Controls.Add(this.btns);
			base.Controls.Add(this.btnr);
			base.Controls.Add(this.btnq);
			base.Controls.Add(this.btnp);
			base.Controls.Add(this.btno);
			base.Controls.Add(this.btnn);
			base.Controls.Add(this.btnz);
			base.Controls.Add(this.btna);
			base.Controls.Add(this.btnm);
			base.Controls.Add(this.btnl);
			base.Controls.Add(this.btnk);
			base.Controls.Add(this.btnj);
			base.Controls.Add(this.btni);
			base.Controls.Add(this.btnh);
			base.Controls.Add(this.btng);
			base.Controls.Add(this.btnf);
			base.Controls.Add(this.btne);
			base.Controls.Add(this.btnd);
			base.Controls.Add(this.btnc);
			base.Controls.Add(this.btnb);
			base.Controls.Add(this.btn6);
			base.Controls.Add(this.btn5);
			base.Controls.Add(this.btn4);
			base.Controls.Add(this.btn3);
			base.Controls.Add(this.btn2);
			base.Controls.Add(this.btn1);
			base.Controls.Add(this.btnd1);
			base.Controls.Add(this.btn0);
			base.Controls.Add(this.btn9);
			base.Controls.Add(this.btn8);
			base.Controls.Add(this.btn7);
			base.Controls.Add(this.btnShift);
			base.Controls.Add(this.btnClose);
			base.Controls.Add(this.btnCapsLock);
			base.Controls.Add(this.btnDelet);
			base.FormBorderStyle = FormBorderStyle.None;
			base.Margin = new Padding(4, 3, 4, 3);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "PassKey";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			this.Text = "QQ";
			base.TopMost = true;
			base.Deactivate += new EventHandler(this.PassKey_Deactivate);
			base.FormClosing += new FormClosingEventHandler(this.PassKey_FormClosing);
			base.Load += new EventHandler(this.PassKey_Load);
			base.ResumeLayout(false);
		}
		public PassKey(int x, int y, SkinTextBox txt)
		{
			this.InitializeComponent();
			this.txt = txt;
			this.X = x;
			this.Y = y;
			this.SetStyles();
		}
		protected override void OnPaint(PaintEventArgs e)
		{
			UpdateForm.CreateRegion(this, 4);
			base.OnPaint(e);
		}
		private void SetStyles()
		{
			base.SetStyle(ControlStyles.UserPaint | ControlStyles.ResizeRedraw | ControlStyles.AllPaintingInWmPaint | ControlStyles.DoubleBuffer | ControlStyles.OptimizedDoubleBuffer, true);
			base.UpdateStyles();
		}
		private void PassKey_Deactivate(object sender, EventArgs e)
		{
			base.Close();
		}
		private void btnClose_Click(object sender, EventArgs e)
		{
			base.Close();
		}
		private void btnDelet_Click(object sender, EventArgs e)
		{
			if (this.txt.Text.Length > 0)
			{
				this.txt.Text = this.txt.Text.Substring(0, this.txt.Text.Length - 1);
			}
		}
		private void btn_Click(object sender, EventArgs e)
		{
			SkinButtom skinButtom = (SkinButtom)sender;
			this.txt.AppendText((skinButtom.Text == "&&") ? "&" : skinButtom.Text);
		}
		private void btnCapsLock_Click(object sender, EventArgs e)
		{
			this.ToUpper = !this.ToUpper;
			this.flag = !this.flag;
			foreach (SkinButtom skinButtom in base.Controls)
			{
				if (skinButtom.Tag.ToString() == "2")
				{
					skinButtom.Text = (this.ToUpper ? skinButtom.Text.ToUpper() : skinButtom.Text.ToLower());
				}
			}
			if (this.flag)
			{
				this.Norml = this.btnCapsLock.NormlBack;
				this.Mouse = this.btnCapsLock.MouseBack;
				this.btnCapsLock.NormlBack = this.btnCapsLock.DownBack;
				this.btnCapsLock.MouseBack = this.btnCapsLock.DownBack;
				return;
			}
			this.btnCapsLock.NormlBack = this.Norml;
			this.btnCapsLock.MouseBack = this.Mouse;
		}
		private void btnShift_Click(object sender, EventArgs e)
		{
			this.ToUpper = !this.ToUpper;
			this.flag2 = !this.flag2;
			foreach (SkinButtom skinButtom in base.Controls)
			{
				if (skinButtom.Tag.ToString() == "2")
				{
					skinButtom.Text = (this.ToUpper ? skinButtom.Text.ToUpper() : skinButtom.Text.ToLower());
				}
			}
			foreach (SkinButtom skinButtom2 in base.Controls)
			{
				if (skinButtom2.Tag.ToString().Substring(0, 1) == "1")
				{
					if (skinButtom2.Text == "7")
					{
						skinButtom2.Text = "&&";
					}
					else
					{
						skinButtom2.Text = (this.flag2 ? skinButtom2.Tag.ToString().Substring(1, 1) : skinButtom2.Tag.ToString().Substring(2));
					}
				}
			}
			if (this.flag2)
			{
				this.Norml2 = this.btnShift.NormlBack;
				this.Mouse2 = this.btnShift.MouseBack;
				this.btnShift.NormlBack = this.btnShift.DownBack;
				this.btnShift.MouseBack = this.btnShift.DownBack;
				return;
			}
			this.btnShift.NormlBack = this.Norml2;
			this.btnShift.MouseBack = this.Mouse2;
		}
		private void PassKey_FormClosing(object sender, FormClosingEventArgs e)
		{
			NativeMethods.AnimateWindow(base.Handle, 0, 589824);
		}
		private void PassKey_Load(object sender, EventArgs e)
		{
			base.Location = new Point(this.X, this.Y);
			NativeMethods.AnimateWindow(base.Handle, 0, 786432);
		}
	}
}
